//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationLoginApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public string CustomerId { get; set; }
        public string Title { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string UserName { get; set; }
        public string LName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Mobile { get; set; }
        public string PaymentMode { get; set; }
        public string CreditCardNo { get; set; }
        public string Address { get; set; }
        public string CompanyName { get; set; }
        public string BusinessAddress { get; set; }
        public string PassportNo { get; set; }
        public string Nationality { get; set; }
        public string CheckedBy { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
    }
}
